package github_test

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"reflect"
	"strings"
	"testing"

	"github.com/rcpassos/mergeyard/internal/github"
)

func pullRequestJSON(number int, draft bool, body string) []byte {
	return []byte(fmt.Sprintf(`{"number":%d,"html_url":"https://github.com/rcpassos/mergeyard/pull/%d","state":"open","draft":%t,"body":%q,"head":{"ref":"mergeyard/issue-12","repo":{"full_name":"rcpassos/mergeyard"}}}`, number, number, draft, body))
}

func TestGeneratePullRequestBody(t *testing.T) {
	body, err := github.GeneratePullRequestBody(github.PullRequestContent{
		IssueNumber: 12, IssueTitle: "GitHub adapter: pull requests",
		Summary: "Added PR discovery and updates.\n\nVerified with unit tests.", RunID: "run-123",
	})
	if err != nil {
		t.Fatal(err)
	}
	want := "<!-- mergeyard:generated:start -->\nCloses #12\n\nAdded PR discovery and updates.\n\nVerified with unit tests.\n\n---\nGenerated by Mergeyard. Run ID: `run-123`.\n<!-- mergeyard:generated:end -->"
	if body != want {
		t.Fatalf("body = %q, want %q", body, want)
	}
}

func TestUpdatePullRequestBodyPreservesUserText(t *testing.T) {
	content := github.PullRequestContent{IssueNumber: 12, IssueTitle: "Pull requests", Summary: "New summary", RunID: "run-456"}
	generated := "<!-- mergeyard:generated:start -->\nCloses #12\n\nNew summary\n\n---\nGenerated by Mergeyard. Run ID: `run-456`.\n<!-- mergeyard:generated:end -->"
	prefix := "User introduction.\r\n\r\n"
	suffix := "\n\nUser checklist: $(touch /tmp/injected); `id`\n"
	old := "<!-- mergeyard:generated:start -->\nOld summary\n<!-- mergeyard:generated:end -->"
	for _, tc := range []struct{ name, body, want string }{
		{"replace", prefix + old + suffix, prefix + generated + suffix},
		{"append", prefix + suffix, prefix + suffix + "\n\n" + generated},
		{"empty", "", generated},
		{"unchanged", prefix + generated + suffix, prefix + generated + suffix},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got, err := github.UpdatePullRequestBody(tc.body, content)
			if err != nil || got != tc.want {
				t.Fatalf("body = %q, error = %v; want %q", got, err, tc.want)
			}
		})
	}
}

func TestFindOpenPullRequest(t *testing.T) {
	pr := string(pullRequestJSON(24, true, "User body"))
	fork := strings.ReplaceAll(pr, `"rcpassos/mergeyard"`, `"someone/fork"`)
	otherBranch := strings.ReplaceAll(pr, "mergeyard/issue-12", "unrelated")
	closed := strings.ReplaceAll(pr, `"state":"open"`, `"state":"closed"`)
	for _, tc := range []struct {
		name, data string
		want       int
		code       string
	}{
		{"none", "[]", 0, ""},
		{"one on later page", "[" + fork + "," + otherBranch + "," + closed + "] [" + pr + "]", 24, ""},
		{"multiple pages", "[" + pr + "] [" + string(pullRequestJSON(25, false, "")) + "]", 0, "pr.multiple_open"},
		{"invalid later page", "[" + pr + "] {}", 0, "github.invalid_response"},
		{"empty response", "", 0, "github.invalid_response"},
		{"missing identity", "[{}]", 0, "github.invalid_response"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			runner := &recordedGH{responses: []response{{stdout: []byte(tc.data)}}}
			got, err := github.New(runner).FindOpenPullRequest(context.Background(), "rcpassos/mergeyard", "mergeyard/issue-12")
			if tc.code != "" {
				requireCode(t, err, tc.code)
				return
			}
			if err != nil {
				t.Fatal(err)
			}
			if tc.want == 0 {
				if got != nil {
					t.Fatalf("unexpected PR: %+v", got)
				}
			} else if got == nil || got.Number != tc.want || !got.Draft || got.Body != "User body" || got.URL != "https://github.com/rcpassos/mergeyard/pull/24" {
				t.Fatalf("unexpected PR: %+v", got)
			}
			call := runner.calls[0]
			if !contains(call.args, "repos/rcpassos/mergeyard/pulls?head=rcpassos%3Amergeyard%2Fissue-12&per_page=100&state=open") || !contains(call.args, "--paginate") || len(call.input) != 0 {
				t.Fatalf("expected paginated branch lookup: %+v", call)
			}
		})
	}
}

func TestCreateDraftPullRequestUsesJSONStdin(t *testing.T) {
	content := github.PullRequestContent{IssueNumber: 12, IssueTitle: "Literal $(touch /tmp/injected); `id`", Summary: "Summary with 'quotes', \"double quotes\", $HOME and\nnewlines.", RunID: "run-123"}
	runner := &recordedGH{responses: []response{{stdout: pullRequestJSON(24, true, "Created body")}}}
	pr, err := github.New(runner).CreateDraftPullRequest(context.Background(), "rcpassos/mergeyard", "mergeyard/issue-12", "main", content)
	if err != nil || pr == nil || pr.Number != 24 || !pr.Draft || pr.Body != "Created body" {
		t.Fatalf("PR = %+v, error = %v", pr, err)
	}
	call := runner.calls[0]
	var payload struct {
		Title, Head, Base, Body string
		Draft                   bool
	}
	if err := json.Unmarshal(call.input, &payload); err != nil {
		t.Fatal(err)
	}
	if payload.Title != "#12 "+content.IssueTitle || payload.Head != "mergeyard/issue-12" || payload.Base != "main" || !payload.Draft || !strings.Contains(payload.Body, content.Summary) || !strings.Contains(payload.Body, "Closes #12") || !strings.Contains(payload.Body, "run-123") {
		t.Fatalf("unexpected payload: %+v", payload)
	}
	if !contains(call.args, "POST") || !contains(call.args, "repos/rcpassos/mergeyard/pulls") || !contains(call.args, "--input") || !contains(call.args, "-") || strings.Contains(strings.Join(call.args, " "), "injected") || strings.Contains(strings.Join(call.args, " "), "Summary") {
		t.Fatalf("body/title did not stay in JSON stdin: %+v", call)
	}
}

func TestCreatePullRequestFallsBackOnlyWhenDraftsUnsupported(t *testing.T) {
	content := github.PullRequestContent{IssueNumber: 12, IssueTitle: "Pull requests", Summary: "Implemented", RunID: "run-123"}
	runner := &recordedGH{responses: []response{
		{stderr: []byte("gh: Draft pull requests are not supported in this repository. (HTTP 422)"), err: errors.New("exit status 1")},
		{stdout: pullRequestJSON(24, false, "Created body")},
	}}
	pr, err := github.New(runner).CreateDraftPullRequest(context.Background(), "rcpassos/mergeyard", "mergeyard/issue-12", "main", content)
	if err != nil || pr == nil || pr.Draft {
		t.Fatalf("PR = %+v, error = %v", pr, err)
	}
	if len(runner.calls) != 2 {
		t.Fatalf("calls = %d, want 2", len(runner.calls))
	}
	var first, second map[string]any
	if err := json.Unmarshal(runner.calls[0].input, &first); err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(runner.calls[1].input, &second); err != nil {
		t.Fatal(err)
	}
	if first["draft"] != true || second["draft"] != false {
		t.Fatalf("draft flags = %v, %v", first["draft"], second["draft"])
	}
	delete(first, "draft")
	delete(second, "draft")
	if !reflect.DeepEqual(first, second) {
		t.Fatalf("fallback changed content: %v / %v", first, second)
	}
}

func TestUpdatePullRequestReadsLatestBodyAndChangesOnlyGeneratedSection(t *testing.T) {
	content := github.PullRequestContent{IssueNumber: 12, IssueTitle: "Pull requests", Summary: "New summary", RunID: "run-456"}
	old := "User introduction.\r\n\r\n<!-- mergeyard:generated:start -->\nOld summary\n<!-- mergeyard:generated:end -->\n\nUser checklist.\n"
	want := "User introduction.\r\n\r\n<!-- mergeyard:generated:start -->\nCloses #12\n\nNew summary\n\n---\nGenerated by Mergeyard. Run ID: `run-456`.\n<!-- mergeyard:generated:end -->\n\nUser checklist.\n"
	runner := &recordedGH{responses: []response{{stdout: pullRequestJSON(24, true, old)}, {stdout: pullRequestJSON(24, true, want)}}}
	pr, err := github.New(runner).UpdatePullRequest(context.Background(), "rcpassos/mergeyard", 24, content)
	if err != nil || pr == nil || pr.Body != want {
		t.Fatalf("PR = %+v, error = %v", pr, err)
	}
	if len(runner.calls) != 2 || !contains(runner.calls[0].args, "GET") || !contains(runner.calls[0].args, "repos/rcpassos/mergeyard/pulls/24") || !contains(runner.calls[1].args, "PATCH") || !contains(runner.calls[1].args, "--input") {
		t.Fatalf("expected read then update: %+v", runner.calls)
	}
	var payload map[string]string
	if err := json.Unmarshal(runner.calls[1].input, &payload); err != nil {
		t.Fatal(err)
	}
	if len(payload) != 1 || payload["body"] != want {
		t.Fatalf("updated more than generated body: %v", payload)
	}
	if strings.Contains(strings.Join(runner.calls[1].args, " "), "User") {
		t.Fatal("body reached argv")
	}
}

// Model a PATCH that applies remotely, followed by a human edit before the
// client receives an ambiguous failure. Replaying the payload erases that edit.
type editedPullRequest struct {
	body    string
	patches int
	stderr  string
	failure error
}

func (r *editedPullRequest) Run(_ context.Context, input []byte, args ...string) ([]byte, []byte, error) {
	if contains(args, "GET") {
		return pullRequestJSON(24, true, r.body), nil, nil
	}
	if !contains(args, "PATCH") {
		return nil, nil, fmt.Errorf("unexpected command: %v", args)
	}
	var payload struct {
		Body string `json:"body"`
	}
	if err := json.Unmarshal(input, &payload); err != nil {
		return nil, nil, err
	}
	r.patches++
	r.body = payload.Body
	if r.patches == 1 {
		r.body += "\n\nHuman edit made after the PATCH applied.\n"
		return nil, []byte(r.stderr), r.failure
	}
	return pullRequestJSON(24, true, r.body), nil, nil
}

func TestPullRequestUpdatePreservesHumanEditAfterAmbiguousFailure(t *testing.T) {
	for _, stderr := range []string{"gh: Bad Gateway (HTTP 502)", "connection reset by peer", "i/o timeout"} {
		t.Run(stderr, func(t *testing.T) {
			cause := errors.New("exit status 1")
			runner := &editedPullRequest{
				body:   "User introduction.\n\n<!-- mergeyard:generated:start -->\nOld summary\n<!-- mergeyard:generated:end -->",
				stderr: stderr, failure: cause,
			}
			content := github.PullRequestContent{IssueNumber: 12, IssueTitle: "Pull requests", Summary: "New summary", RunID: "run-456"}
			client := github.New(runner)
			pr, err := client.UpdatePullRequest(context.Background(), "rcpassos/mergeyard", 24, content)
			if !strings.HasSuffix(runner.body, "\n\nHuman edit made after the PATCH applied.\n") {
				t.Fatalf("human edit erased by a stale PATCH retry: %q", runner.body)
			}
			requireCode(t, err, "github.unavailable")
			if pr != nil || !errors.Is(err, cause) || runner.patches != 1 {
				t.Fatalf("ambiguous failure = %+v, %v; PATCH count = %d", pr, err, runner.patches)
			}
			// A new caller attempt reads the edited body, recognizes the applied
			// generated section, and succeeds without replaying the old snapshot.
			pr, err = client.UpdatePullRequest(context.Background(), "rcpassos/mergeyard", 24, content)
			if err != nil || pr == nil || pr.Body != runner.body || runner.patches != 1 {
				t.Fatalf("reconciliation = %+v, %v; PATCH count = %d", pr, err, runner.patches)
			}
		})
	}
}

func TestPullRequestBodyRejectsAmbiguousMarkers(t *testing.T) {
	content := github.PullRequestContent{IssueNumber: 12, IssueTitle: "Pull requests", Summary: "Summary", RunID: "run-123"}
	for _, body := range []string{
		"User text <!-- mergeyard:generated:start --> orphan",
		"User text <!-- mergeyard:generated:end --> orphan",
		"<!-- mergeyard:generated:end --><!-- mergeyard:generated:start -->",
		"<!-- mergeyard:generated:start --><!-- mergeyard:generated:start --><!-- mergeyard:generated:end -->",
		"<!-- mergeyard:generated:start --><!-- mergeyard:generated:end --><!-- mergeyard:generated:end -->",
	} {
		_, err := github.UpdatePullRequestBody(body, content)
		requireCode(t, err, "pr.invalid_generated_section")
		runner := &recordedGH{responses: []response{{stdout: pullRequestJSON(24, true, body)}}}
		_, err = github.New(runner).UpdatePullRequest(context.Background(), "rcpassos/mergeyard", 24, content)
		requireCode(t, err, "pr.invalid_generated_section")
		if len(runner.calls) != 1 {
			t.Fatal("malformed body was overwritten")
		}
	}
}

func TestPullRequestInvalidInputsDoNotInvokeGH(t *testing.T) {
	valid := github.PullRequestContent{IssueNumber: 12, IssueTitle: "Pull requests", Summary: "Summary", RunID: "run-123"}
	for _, content := range []github.PullRequestContent{
		{IssueTitle: valid.IssueTitle, Summary: valid.Summary, RunID: valid.RunID},
		{IssueNumber: 12, Summary: valid.Summary, RunID: valid.RunID},
		{IssueNumber: 12, IssueTitle: valid.IssueTitle, RunID: valid.RunID},
		{IssueNumber: 12, IssueTitle: valid.IssueTitle, Summary: valid.Summary},
		{IssueNumber: 12, IssueTitle: valid.IssueTitle, Summary: valid.Summary, RunID: "run\n123"},
		{IssueNumber: 12, IssueTitle: valid.IssueTitle, Summary: "<!-- mergeyard:generated:end -->", RunID: valid.RunID},
	} {
		runner := &recordedGH{}
		_, err := github.GeneratePullRequestBody(content)
		requireCode(t, err, "github.invalid_input")
		_, err = github.New(runner).CreateDraftPullRequest(context.Background(), "rcpassos/mergeyard", "branch", "main", content)
		requireCode(t, err, "github.invalid_input")
		_, err = github.New(runner).UpdatePullRequest(context.Background(), "rcpassos/mergeyard", 24, content)
		requireCode(t, err, "github.invalid_input")
	}
	runner := &recordedGH{}
	client := github.New(runner)
	for _, repo := range []string{"", "owner/..", "owner/repo?state=all"} {
		_, err := client.FindOpenPullRequest(context.Background(), repo, "branch")
		requireCode(t, err, "github.invalid_input")
		_, err = client.CreateDraftPullRequest(context.Background(), repo, "branch", "main", valid)
		requireCode(t, err, "github.invalid_input")
		_, err = client.UpdatePullRequest(context.Background(), repo, 24, valid)
		requireCode(t, err, "github.invalid_input")
	}
	_, err := client.FindOpenPullRequest(context.Background(), "rcpassos/mergeyard", " ")
	requireCode(t, err, "github.invalid_input")
	_, err = client.CreateDraftPullRequest(context.Background(), "rcpassos/mergeyard", "", "main", valid)
	requireCode(t, err, "github.invalid_input")
	_, err = client.CreateDraftPullRequest(context.Background(), "rcpassos/mergeyard", "branch", "", valid)
	requireCode(t, err, "github.invalid_input")
	_, err = client.UpdatePullRequest(context.Background(), "rcpassos/mergeyard", 0, valid)
	requireCode(t, err, "github.invalid_input")
}

func TestPullRequestCreationDoesNotRetryOtherFailures(t *testing.T) {
	content := github.PullRequestContent{IssueNumber: 12, IssueTitle: "Pull requests", Summary: "Summary", RunID: "run-123"}
	for _, tc := range []struct{ stderr, code string }{
		{"gh: Validation Failed (HTTP 422)", "github.command_failed"},
		{"gh: Forbidden (HTTP 403)", "github.forbidden"},
		{"gh: Bad Gateway (HTTP 502)", "github.unavailable"},
		{"connection reset by peer", "github.unavailable"},
		{"gh: Draft pull requests are not supported in this repository. (HTTP 500)", "github.unavailable"},
	} {
		t.Run(tc.stderr, func(t *testing.T) {
			cause := errors.New("exit status 1")
			runner := &recordedGH{responses: []response{{stderr: []byte(tc.stderr), err: cause}}}
			_, err := github.New(runner).CreateDraftPullRequest(context.Background(), "rcpassos/mergeyard", "branch", "main", content)
			requireCode(t, err, tc.code)
			if !errors.Is(err, cause) || len(runner.calls) != 1 {
				t.Fatalf("cause or retry policy lost: %v / %+v", err, runner.calls)
			}
		})
	}
}

func TestPullRequestCreationFallbackFailureIsReturned(t *testing.T) {
	runner := &recordedGH{responses: []response{
		{stderr: []byte("gh: Draft pull requests are not supported in this repository. (HTTP 422)"), err: errors.New("exit status 1")},
		{stderr: []byte("gh: Forbidden (HTTP 403)"), err: errors.New("exit status 1")},
	}}
	_, err := github.New(runner).CreateDraftPullRequest(context.Background(), "rcpassos/mergeyard", "branch", "main", github.PullRequestContent{IssueNumber: 12, IssueTitle: "Pull requests", Summary: "Summary", RunID: "run-123"})
	requireCode(t, err, "github.forbidden")
}

func TestPullRequestUpdateSkipsUnchangedBody(t *testing.T) {
	content := github.PullRequestContent{IssueNumber: 12, IssueTitle: "Pull requests", Summary: "Summary", RunID: "run-123"}
	body := "<!-- mergeyard:generated:start -->\nCloses #12\n\nSummary\n\n---\nGenerated by Mergeyard. Run ID: `run-123`.\n<!-- mergeyard:generated:end -->"
	runner := &recordedGH{responses: []response{{stdout: pullRequestJSON(24, true, body)}}}
	pr, err := github.New(runner).UpdatePullRequest(context.Background(), "rcpassos/mergeyard", 24, content)
	if err != nil || pr.Body != body || len(runner.calls) != 1 {
		t.Fatalf("unchanged update = %+v, %v, calls = %d", pr, err, len(runner.calls))
	}
}

func TestPullRequestResponseFailures(t *testing.T) {
	content := github.PullRequestContent{IssueNumber: 12, IssueTitle: "Pull requests", Summary: "Summary", RunID: "run-123"}
	for _, data := range []string{"", "null", "{}", "[]", `{"number":24}`, strings.ReplaceAll(string(pullRequestJSON(24, true, "")), `"open"`, `"unknown"`)} {
		for _, operation := range []string{"create", "update"} {
			t.Run(operation+data, func(t *testing.T) {
				runner := &recordedGH{responses: []response{{stdout: []byte(data)}}}
				client := github.New(runner)
				var err error
				if operation == "create" {
					_, err = client.CreateDraftPullRequest(context.Background(), "rcpassos/mergeyard", "branch", "main", content)
				} else {
					_, err = client.UpdatePullRequest(context.Background(), "rcpassos/mergeyard", 24, content)
				}
				requireCode(t, err, "github.invalid_response")
			})
		}
	}
	for _, mutate := range []bool{false, true} {
		responses := []response{{stderr: []byte("gh: Forbidden (HTTP 403)"), err: errors.New("exit status 1")}}
		if mutate {
			responses = append([]response{{stdout: pullRequestJSON(24, true, "User text")}}, responses...)
		}
		runner := &recordedGH{responses: responses}
		_, err := github.New(runner).UpdatePullRequest(context.Background(), "rcpassos/mergeyard", 24, content)
		requireCode(t, err, "github.forbidden")
	}
}

func TestPullRequestsRespectCanceledContext(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	runner := &recordedGH{}
	client := github.New(runner)
	content := github.PullRequestContent{IssueNumber: 12, IssueTitle: "Pull requests", Summary: "Summary", RunID: "run-123"}
	_, err := client.FindOpenPullRequest(ctx, "rcpassos/mergeyard", "branch")
	requireCode(t, err, "github.canceled")
	_, err = client.CreateDraftPullRequest(ctx, "rcpassos/mergeyard", "branch", "main", content)
	requireCode(t, err, "github.canceled")
	_, err = client.UpdatePullRequest(ctx, "rcpassos/mergeyard", 24, content)
	requireCode(t, err, "github.canceled")
}
